# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm-9"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["cd apps/web && NODE_OPTIONS='--require ./node-polyfill.cjs' pnpm build"]

[start]
cmd = "cd apps/web && pnpm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"