# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm-9"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "cd apps/web && pnpm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"