packages:
  - 'apps/*'
  - 'packages/*'
  - '!packages/blockchain'
  # Include experimental packages referenced by apps/web for lint/typecheck
  - '!packages/plugins'
  - 'infra/*'
  - 'scripts'
  - 'bin'
