import { ThemeConfig } from '../src/types';

export const baseThemeConfig: ThemeConfig = {
  id: 'base',
  name: 'Base Theme',
  description: 'Foundation theme for AffiliateOS - neutral and versatile for any niche',
  version: '1.0.0',
  author: 'AffiliateOS',
  category: 'minimal',
  tags: ['clean', 'modern', 'versatile', 'responsive'],
  colors: {
    primary: '#3B82F6',
    secondary: '#8B5CF6',
    accent: '#F59E0B',
    background: '#FFFFFF',
    foreground: '#0F172A',
    muted: '#F1F5F9',
    mutedForeground: '#64748B',
    border: '#E2E8F0',
    ring: '#3B82F6',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
    info: '#06B6D4',
  },
  typography: {
    fontFamily: {
      sans: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      serif: 'Georgia, Cambria, "Times New Roman", Times, serif',
      mono: 'SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
    },
    fontWeight: {
      thin: 100,
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
    },
    lineHeight: {
      tight: '1.25',
      normal: '1.5',
      relaxed: '1.75',
    },
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
  },
  borderRadius: {
    none: '0',
    sm: '0.125rem',
    md: '0.375rem',
    lg: '0.5rem',
    full: '9999px',
  },
  shadows: {
    sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    md: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
  },
  animations: {
    duration: {
      fast: '150ms',
      normal: '300ms',
      slow: '500ms',
    },
    easing: {
      ease: 'ease',
      easeIn: 'ease-in',
      easeOut: 'ease-out',
      easeInOut: 'ease-in-out',
    },
  },
  layout: {
    maxWidth: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
      full: '100%',
    },
    container: {
      padding: '1rem',
    },
    grid: {
      columns: 12,
      gap: '1.5rem',
    },
  },
  components: {
    button: {
      variants: {
        primary: 'bg-primary text-white hover:bg-primary/90',
        secondary: 'bg-secondary text-white hover:bg-secondary/90',
        outline: 'border border-border hover:bg-muted',
        ghost: 'hover:bg-muted',
        destructive: 'bg-error text-white hover:bg-error/90',
      },
      sizes: {
        sm: 'px-3 py-1.5 text-sm',
        md: 'px-4 py-2',
        lg: 'px-6 py-3 text-lg',
      },
    },
    card: {
      background: 'bg-white',
      border: 'border border-border',
      shadow: 'shadow-md',
      radius: 'rounded-lg',
    },
    input: {
      background: 'bg-white',
      border: 'border border-border',
      focus: 'focus:ring-2 focus:ring-primary focus:border-primary',
      placeholder: 'placeholder:text-muted-foreground',
    },
    navigation: {
      background: 'bg-white',
      text: 'text-foreground',
      hover: 'hover:text-primary',
      active: 'text-primary font-semibold',
    },
  },
  settings: {
    primaryColor: {
      type: 'color',
      label: 'Primary Color',
      description: 'Main brand color',
      default: '#3B82F6',
    },
    fontFamily: {
      type: 'select',
      label: 'Font Family',
      description: 'Primary font for content',
      default: 'Inter',
      options: [
        { value: 'Inter', label: 'Inter' },
        { value: 'Roboto', label: 'Roboto' },
        { value: 'Open Sans', label: 'Open Sans' },
        { value: 'Lato', label: 'Lato' },
        { value: 'Poppins', label: 'Poppins' },
      ],
    },
    borderRadius: {
      type: 'select',
      label: 'Border Radius',
      description: 'Corner roundness',
      default: 'md',
      options: [
        { value: 'none', label: 'Sharp' },
        { value: 'sm', label: 'Subtle' },
        { value: 'md', label: 'Medium' },
        { value: 'lg', label: 'Rounded' },
      ],
    },
    darkMode: {
      type: 'boolean',
      label: 'Dark Mode',
      description: 'Enable dark mode support',
      default: true,
    },
  },
};