import Link from 'next/link';
import { notFound } from 'next/navigation';
import { NewsletterBar, QuizDrawer } from '@affiliate-factory/ui';
import type { Quiz, Product } from '@affiliate-factory/sdk';
import { getTenantBySlug } from '../../../lib/tenant';
import { getActiveQuiz, getFeaturedProducts, getRecentPosts, getTenantInsights } from '../../../lib/content';
import { submitQuizAnswers, subscribeToNewsletter } from './actions';
import { ProductCard } from '../../../components/ProductCard';
import { CategoryNavigation } from '../../../components/CategoryNavigation';
import { TestimonialsSection } from '../../../components/TestimonialsSection';
import { FAQSection } from '../../../components/FAQSection';
import { CheckCircleIcon, TruckIcon, ShieldCheckIcon } from '@heroicons/react/24/outline';

interface TenantPageProps {
  params: { tenantSlug: string };
}

// Categories for the horizontal scroll with pinning
const categories = [
  { id: 'featured', name: 'Featured', pinned: true },
  { id: 'smartwatches', name: 'Smartwatches' },
  { id: 'fitness-trackers', name: 'Fitness Trackers' },
  { id: 'health-monitors', name: 'Health Monitors' },
  { id: 'smart-rings', name: 'Smart Rings' },
  { id: 'sleep-trackers', name: 'Sleep Trackers' },
  { id: 'posture-devices', name: 'Posture Devices' },
  { id: 'smart-glasses', name: 'Smart Glasses' },
  { id: 'accessories', name: 'Accessories' },
];

const testimonials = [
  {
    id: 1,
    name: 'Sarah Johnson',
    role: 'Fitness Enthusiast',
    content: 'Found the perfect smartwatch through this site. The comparison tools and honest reviews helped me make the right choice.',
    rating: 5,
  },
  {
    id: 2,
    name: 'Mike Chen',
    role: 'Tech Professional',
    content: 'Best resource for wearable tech. Always up-to-date with the latest products and great deals on Amazon.',
    rating: 5,
  },
  {
    id: 3,
    name: 'Emily Rodriguez',
    role: 'Health Coach',
    content: 'My go-to site for recommending fitness trackers to clients. The detailed guides are incredibly helpful.',
    rating: 5,
  },
];

const faqs = [
  {
    question: 'How do you select products?',
    answer: 'Our AI-powered system analyzes thousands of products nightly, evaluating reviews, specifications, and price history to recommend only the best wearable tech.',
  },
  {
    question: 'Are the prices updated regularly?',
    answer: 'Yes! Prices sync directly with Amazon every night through their official PA-API, ensuring you always see current pricing and availability.',
  },
  {
    question: 'Do you earn from purchases?',
    answer: 'Yes, we earn a small commission from Amazon when you buy through our links (affiliate tag: jmpkc01-20). This doesn\'t affect your price.',
  },
  {
    question: 'Can I trust the reviews?',
    answer: 'Absolutely. Our reviews are generated by analyzing verified purchase reviews and expert opinions, providing balanced and honest assessments.',
  },
];

export default async function TenantHomePage({ params }: TenantPageProps) {
  const { tenantSlug } = await params;
  const tenant = await getTenantBySlug(tenantSlug);
  if (!tenant) {
    notFound();
  }

  const [products, posts, quiz, insights] = await Promise.all([
    getFeaturedProducts(tenant.id),
    getRecentPosts(tenant.id),
    getActiveQuiz(tenant.id),
    getTenantInsights(tenant.id)
  ]);

  return (
    <>
      {/* Hero Section */}
      <WoodstockHero tenant={tenant} tenantSlug={tenantSlug} />
      
      {/* Category Navigation with Pinning */}
      <CategoryNavigation categories={categories} />
      
      {/* Products by Category */}
      <div className="mx-auto max-w-7xl px-4 py-8">
        <ProductsByCategory products={products} tenantSlug={tenantSlug} />
      </div>

      {/* Trust Badges */}
      <div className="bg-gray-50 py-12">
        <div className="mx-auto max-w-7xl px-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="text-center">
              <ShieldCheckIcon className="h-12 w-12 mx-auto text-green-600 mb-3" />
              <h3 className="font-semibold mb-2">Verified Products</h3>
              <p className="text-sm text-gray-600">Every product verified nightly via Amazon PA-API</p>
            </div>
            <div className="text-center">
              <TruckIcon className="h-12 w-12 mx-auto text-blue-600 mb-3" />
              <h3 className="font-semibold mb-2">Fast Shipping</h3>
              <p className="text-sm text-gray-600">Prime eligible products with 2-day delivery</p>
            </div>
            <div className="text-center">
              <CheckCircleIcon className="h-12 w-12 mx-auto text-purple-600 mb-3" />
              <h3 className="font-semibold mb-2">Expert Curation</h3>
              <p className="text-sm text-gray-600">AI-powered selection from thousands of options</p>
            </div>
          </div>
        </div>
      </div>

      {/* Testimonials */}
      <TestimonialsSection testimonials={testimonials} />
      
      {/* Blog Posts */}
      <div className="mx-auto max-w-7xl px-4 py-12">
        <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between mb-8">
          <div>
            <h2 className="text-3xl font-bold text-neutral-900">Latest Insights</h2>
            <p className="text-gray-600 mt-2">Expert guides and product comparisons</p>
          </div>
          <Link href={`/${tenantSlug}/blog`} className="text-blue-600 font-semibold hover:underline">
            View all posts →
          </Link>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {posts.slice(0, 3).map((post) => (
            <article key={post.id} className="bg-white rounded-lg shadow-sm hover:shadow-md transition-shadow p-6">
              <p className="text-xs font-semibold uppercase tracking-wide text-blue-600">{post.type}</p>
              <h3 className="mt-3 text-lg font-semibold text-neutral-900">
                <Link href={`/${tenantSlug}/blog/${post.slug}`} className="hover:text-blue-600">
                  {post.title}
                </Link>
              </h3>
              <p className="mt-2 text-sm text-gray-600 line-clamp-3">{post.excerpt}</p>
              <Link href={`/${tenantSlug}/blog/${post.slug}`} className="mt-4 inline-flex text-sm font-semibold text-blue-600 hover:underline">
                Read more →
              </Link>
            </article>
          ))}
        </div>
      </div>
      
      {/* FAQ Section */}
      <FAQSection faqs={faqs} />

      {/* Newsletter */}
      <div className="bg-blue-600 py-12">
        <div className="mx-auto max-w-7xl px-4">
          {quiz ? <QuizSubscribe quiz={quiz} tenantSlug={tenantSlug} /> : null}
        </div>
      </div>
    </>
  );
}

// Hero Section Component
function WoodstockHero({ tenant, tenantSlug }: { tenant: any; tenantSlug: string }) {
  return (
    <div className="bg-gradient-to-b from-blue-50 to-white">
      <div className="mx-auto max-w-7xl px-4 py-16 sm:py-24">
        <div className="text-center">
          <h1 className="text-4xl sm:text-6xl font-bold text-gray-900 mb-6">
            {tenant.name}
          </h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto mb-8">
            {tenant.theme?.description || 'Discover the best wearable tech curated by AI agents and verified nightly through Amazon'}
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href={`/${tenantSlug}/products`}
              className="inline-flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-full text-white bg-blue-600 hover:bg-blue-700 transition-colors"
            >
              Browse All Products
            </Link>
            <Link
              href={`/${tenantSlug}/quiz`}
              className="inline-flex items-center justify-center px-8 py-3 border border-gray-300 text-base font-medium rounded-full text-gray-700 bg-white hover:bg-gray-50 transition-colors"
            >
              Take Personalization Quiz
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}

// Products Section
function ProductsByCategory({ products, tenantSlug }: { products: Product[]; tenantSlug: string }) {
  return (
    <div className="space-y-12">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-3xl font-bold text-gray-900">Featured Products</h2>
        <Link 
          href={`/${tenantSlug}/products`}
          className="text-blue-600 font-semibold hover:underline"
        >
          View All →
        </Link>
      </div>
      
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        {products.slice(0, 8).map((product) => (
          <ProductCard key={product.id} product={product} />
        ))}
      </div>
    </div>
  );
}

// Quiz Subscribe Section
function QuizSubscribe({ quiz, tenantSlug }: { quiz: Quiz; tenantSlug: string }) {
  return (
    <div className="text-center text-white">
      <h2 className="text-3xl font-bold mb-4">Get Personalized Recommendations</h2>
      <p className="text-blue-100 mb-8 max-w-2xl mx-auto">
        Take our quick quiz to get 3-5 handpicked products that match your needs, delivered to your inbox.
      </p>
      <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
        <QuizDrawer 
          quiz={quiz} 
          onSubmit={(answers) => submitQuizAnswers(tenantSlug, quiz.id, answers)} 
        />
        <NewsletterBar onSubscribe={(email) => subscribeToNewsletter(tenantSlug, email)} />
      </div>
    </div>
  );
}
